name:                todo-hs
version:             0.1.0.0
github:              "peschkaj/todo-hs"
license:             BSD3
author:              "Jeremiah Peschka, Halala Khoshnaw"
maintainer:          "jeremiah.peschka@gmail.com"
copyright:           "2018 Jeremiah Peschka, Halala Khoshnaw"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/peschkaj/todo-hs#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- directory
- text
- brick
- aeson >= 1.3 && < 1.4
- time

library:
  source-dirs: src

executables:
  todo-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - todo-hs

tests:
  todo-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - todo-hs
